### ISSUE TITLE
Uncaught Error: [$injector:unpr] Unknown provider: bProvider <- b

### ISSUE THREAD

**Issue by siddharatha** [forcedotcom/aura-ng#1]
I installed the managed package and tried to access the regionDemoApp , since its a managed package i wasn't able to debug it.

![aura_angular_failure](https://cloud.githubusercontent.com/assets/1488450/5537764/af759e10-8aa7-11e4-81bc-3332f45234c4.png)

**Comment by dchaudhary** [comment]
I am also getting the same error as above explained except that i am getting the value of {{v.someattribute}} and {{v.someattributes}}

**Comment by dutchchasman** [comment]
@dchaudhary you are getting the exact same error in the same location? Or are you saying that you are getting some error that mentions "Cannot read property <something> of"? Is your org on Spring or Summer?

**Comment by dchaudhary** [comment]
I am getting error :Uncaught Error: [$injector:unpr] Unknown provider: bProvider <- b

**Comment by dutchchasman** [comment]
Is this still an issue? I've been unable to find any related problemsor repro case.

**Comment by dchaudhary** [comment]
Hi,
My org is Spring and still getting same error.

**Comment by xnamahx** [comment]
Hi I have the same error, just installed the package and cant access to /aurang/regionDemoApp.app 
![error image](http://imgur.com/o73cMQj)

**Comment by dutchchasman** [comment]
I have never been able to reproduce this problem locally and until now
there has only been a single developer that has encountered it. What type
of org are you installing into (edition, version, etc)? Can you provide a
login in the org that I can use to see the issue live? My direct email is
dchasman@salesforce.com

On Jan 11, 2016, at 23:29, xnamahx <notifications@github.com> wrote:

Hi I have the same error, just installed the package and cant access to
/aurang/regionDemoApp.app
[image: error image]
<https://camo.githubusercontent.com/2b5fcbcf44e61e47effd53f6bf4bb8202ee58f12/687474703a2f2f696d6775722e636f6d2f6f3733634d516a>

—
Reply to this email directly or view it on GitHub
<https://github.com/forcedotcom/aura-ng/issues/1#issuecomment-170786435>.

**Comment by dutchchasman** [comment]
OK - great - made a little progress at least now that I have a repro case to work with.

**Comment by dutchchasman** [comment]
Yay! Finally figured this one out - sorry it took me so long. @xnamahx I've updated your org to the latest version of the AuraNG package and now the sample app runs great even in prod mode. @dchaudhary I know this one has sat for a very long time but its finally fixed if you install the latest version of the package.

**Comment by dchaudhary** [comment]
Thanks Doug
