### ISSUE TITLE
aurang:template not display any component

### ISSUE THREAD

**Issue by KelvinHuangDZ** [forcedotcom/aura-ng#6]
Hi, I just installed the new package. 

This is how i construct the route:
$stateProvider.state('home', {
                url: '/',
                template: "This is home state"
            }).state('state1', {
                url: "/state1",
                templateUrl: "transaction1.html"
            });
}]);
When I'm using <aurang:template> with the component inside, my page not able to display the component:

< aurang:template id="transaction1.html" >
        < c:FF_Form / >
 < /aurang:template >

Can you please advice if I did anything wrong?

**Comment by dutchchasman** [comment]
I believe this is another case of the obfuscation and minification changes that was enhanced recently colliding with injection. Same issue I fixed recently with aurang:region. I'll get this fixed but as a workaround for now you should be able to enable Debug Mode for Lightning Components:

https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/aura_debug_mode.htm

in your org and this should go away.

**Comment by redguardtoo** [comment]
HI, @dutchchasman ,
I enable the debug mode. Looks there is some issue in aura-ng, specifically, it's in inertRegionHelper.js
```javascript
            var desc = component.getDef().getDescriptor().getQualifiedName();
            switch (desc) {
                case "markup://aura:html":
                    ...
                    break;
                case "markup://aura:text":
                    ...
                    break;    
                default:
                    return undefined;  // this line
            }
```

if desc is "markup://c:MyOwnComponent', it's discarded by default statement.

Any solution?

**Comment by dutchchasman** [comment]
For security reasons (template injection XSS vulnerability) aurang:template
content can only contain HTML tags and not custom lightning components.
This was required by salesforce product security but should not represent
an issue. Why are you putting lightning components in an angular template?
This component's purpose is to allow you to embed inline angular templates
inside of a lightning component. If you were to put a lightning component
in there it would be a template generating a template which introduces XSS
vulnerability in an system (double templating). Can you elaborate on what
you are trying to accomplish? It sounds like you really want an
aurang:region instead?

On Jan 26, 2016, at 03:20, chen bin <notifications@github.com> wrote:

HI, @dutchchasman <https://github.com/dutchchasman> ,
I enable the debug mode. Looks there is some issue in aura-ng,
specifically, it's in inertRegionHelper.js

            var desc = component.getDef().getDescriptor().getQualifiedName();
            switch (desc) {
                case "markup://aura:html":
                    ...
                    break;
                case "markup://aura:text":
                    ...
                    break;
                default:
                    return undefined;  // this line
            }

if desc is "markup://c:MyOwnComponent', it's discarded by default statement.

Any solution?

—
Reply to this email directly or view it on GitHub
<https://github.com/forcedotcom/aura-ng/issues/6#issuecomment-174962090>.

**Comment by redguardtoo** [comment]
Thanks. Our plan is to develop the pages/sub-pages with lightning components as  much as possible. This is decided for non-technical reasons, so I cannot change it. But we need a way to handle url router.

The reason we consider aurang:template is we need a way to load sub-pages (sub pages should be rendered by pure lightning technology) with proper url. ui-router is only needed to do the route for sub-pages. 

Is there any solution?
